INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0003,'Sistema de Gest?o de Convoca??es');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0004,'Software de Gest?o de Riscos e Seguran?a do Paciente');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0006,'Sistema de Almoxarifado do Administrativo');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0011,'Sistema de Descentraliza??o de Cr?dito');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0014,'Sistema de Pesquisa de Satisfa??o');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0015,'Sistema de Gest?o de Contratos do SUS');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0018,'Sistema de Gest?o de Patrim?nio');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0024,'Sistema de Ensino e Pesquisa dos Hospitais Universit?rios Federais');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0028,'Sistema de Gest?o de Progress?o');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0038,'Monitoramento de Obras');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0040,'Ouvidoria');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0041,'Auditoria');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0046,'Mutir?o');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0047,'Contratos');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0048,'Sistema de Gerenciamento de Projetos');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0049,'Sistema de Protocolo');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0050,'Sistema de Est?gio de Resid?ncia da Rede Ebserh');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0051,'Painel Modelo de Gest?o DAS');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0052,'Projeto Rede Pesquisa');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0053,'Processo Seletivo');
INSERT INTO sisdm.sistema(siscodigo,sisnome) VALUES(0054,'Corregedoria');

INSERT INTO sisdm.atendimento(atedescricao) VALUES ('Apoio ao usu?rio?');
INSERT INTO sisdm.atendimento(atedescricao) VALUES ('An?lise no c?digo?');
INSERT INTO sisdm.atendimento(atedescricao) VALUES ('Corre??o no c?digo?');
INSERT INTO sisdm.atendimento(atedescricao) VALUES ('Cria??o de script BD?');
INSERT INTO sisdm.atendimento(atedescricao) VALUES ('Altera??o de BD? Quantas tabelas, arquivos ou excel?');
INSERT INTO sisdm.atendimento(atedescricao) VALUES ('Script para atualiza??o de dados? Quantas atualiza??es de dados (um registro de uma ?nica tabela)?');
INSERT INTO sisdm.atendimento(atedescricao) VALUES ('Criado/efetuado alguma consulta (SELECT)? Quantos atributos?');
INSERT INTO sisdm.atendimento(atedescricao) VALUES ('Outros?');

