INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PORTAIS - INTERNET');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PORTAIS - INTRANET');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PORTAL DE SERVIÇOS DE TI');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO AMBULATÓRIO ADMINISTRATIVO');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO AMBULATÓRIO ASSISTENCIAL');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO CIRURGIAS');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO COLABORADOR');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO COMPRAS');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO CONFIGURAÇÕES');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO CONTROLE DO PACIENTE');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO CUSTOS');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO ESTOQUE');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO EXAMES');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO FARMÁCIA');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO FATURAMENTO');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO INTERNAÇÃO');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO PACIENTES');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO POL (PRONTUÁRIO ON-LINE)');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO PRESCRIÇÃO DE ENFERMAGEM');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » MÓDULO PRESCRIÇÃO MÉDICA');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('PROJETO AGHU » PAINEL DE INDICADORES HOSPITALARES');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - AUDITORIA');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - CONTRATOS');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - CORREGEDORIA');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - MONITORAMENTO DE OBRAS');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - MUTIRÃO');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - OUVIDORIA');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - PAINEL MODELO DE GESTÃO DAS');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - PROCESSO SELETIVO');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - PROJETO REDE PESQUISA');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - SISTEMA DE ALMOXARIFADO DO ADMINISTRATIVO');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - SISTEMA DE DESCENTRALIZAÇÃO DE CRÉDITO');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - SISTEMA DE ENSINO E PESQUISA DOS HOSPITAIS UNIVERSITÁRIOS FEDERAIS');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - SISTEMA DE ESTÉGIO DE RESIDÊNCIA DA REDE EBSERH');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - SISTEMA DE GERENCIAMENTO DE PROJETOS');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - SISTEMA DE GESTÃO DE CONTRATOS DO SUS');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - SISTEMA DE GESTÃO DE CONVOCAÇÕES');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - SISTEMA DE GESTÃO DE PATRIMÔNIO');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - SISTEMA DE GESTÃO DE PROGRESSÃO');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - SISTEMA DE PESQUISA DE SATISFAÇÃO');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - SISTEMA DE PROTOCOLO');
INSERT INTO sisdmdsv.sistema(sisnome) VALUES('SIG - SOFTWARE DE GESTÃO DE RISCOS E SEGURANÇA DO PACIENTE');

INSERT INTO sisdmdsv.atendimento(atedescricao) VALUES ('Apoio ao usuário?');
INSERT INTO sisdmdsv.atendimento(atedescricao) VALUES ('Análise no código?');
INSERT INTO sisdmdsv.atendimento(atedescricao) VALUES ('Correção no código?');
INSERT INTO sisdmdsv.atendimento(atedescricao) VALUES ('Criação de script BD?');
INSERT INTO sisdmdsv.atendimento(atedescricao) VALUES ('Alteração de BD? Quantas tabelas, arquivos ou excel?');
INSERT INTO sisdmdsv.atendimento(atedescricao) VALUES ('Script para atualização de dados? Quantas atualizações de dados (um registro de uma única tabela)?');
INSERT INTO sisdmdsv.atendimento(atedescricao) VALUES ('Criado/efetuado alguma consulta (SELECT)? Quantos atributos?');
INSERT INTO sisdmdsv.atendimento(atedescricao) VALUES ('Outros?');

